language: python
python:
  - "2.7"
# command to install dependencies
install:
  - wget -c http://www.cs.helsinki.fi/group/pssmfind/MOODS-1.0.2.1.tar.gz
  - tar xzvf MOODS-1.0.2.1.tar.gz
  - cd MOODS/src
  - make
  - cd ../python
  - python setup.py install
# command to run tests
script:
  - python -m unittest discover
notifications:
  email: false