language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "nightly"

# command to install dependencies
install:
  - git clone https://github.com/jhkorhonen/MOODS.git
  - make -C MOODS/src/
  - cd MOODS/python
  - python setup.py install
  - cd ../..

  - pip install biopython

# command to run tests
script:
  - python -m unittest discover

notifications:
  email: false