language:
  - python

python:
  - "2.7"

# command to install dependencies
install:
  - wget -c http://www.cs.helsinki.fi/group/pssmfind/MOODS-1.0.2.1.tar.gz
  - tar xzvf MOODS-1.0.2.1.tar.gz
  - make -C MOODS/src/
  - cd MOODS/python
  - python setup.py install
  - cd ../..

  - easy_install -f http://biopython.org/DIST/ biopython

# command to run tests
script:
  - python -m unittest discover

notifications:
  email: false