language:
  - python

python:
  - "2.7"
  - "pypy"

# command to install dependencies
install:
  - pip install codecov

  # install MOODS
  - git clone https://github.com/jhkorhonen/MOODS.git
  - make -C MOODS/src/
  - cd MOODS/python
  - python setup.py install
  - cd ../..

  - pip install biopython

  # install bbcflib
  - git clone https://github.com/bbcf/bbcflib.git
  - cd bbcflib/
  - python setup.py install
  - cd ..

# command to run tests
script:
  - coverage run -m unittest discover -b

after_success:
  - codecov

notifications:
  email: false
